import type { AuditReport } from '../core/types'

// Hidden marker so the action can find and update its own comment instead of
// posting a new one on every push.
export const COMMENT_MARKER = '<!-- starforge -->'

const REPO_URL = 'https://github.com/Wang-Yeah623/starforge'

function bar(percent: number): string {
  const filled = Math.round(percent / 10)
  return `${'█'.repeat(filled)}${'░'.repeat(10 - filled)}`
}

export function renderComment(report: AuditReport): string {
  const emoji = report.score >= 82 ? '🟢' : report.score >= 58 ? '🟡' : '🔴'

  const categoryRows = report.categories
    .map((category) => `| ${category.label} | \`${bar(category.percent)}\` | ${category.percent}% |`)
    .join('\n')

  const fixes =
    report.checklist.length > 0
      ? report.checklist.map((fix) => `- ${fix}`).join('\n')
      : '- Nothing blocking — this repo is launch-ready. 🚀'

  return [
    COMMENT_MARKER,
    `## ${emoji} StarForge — ${report.score}/100 · ${report.grade}`,
    '',
    report.summary,
    '',
    '| Category | | |',
    '| :-- | :-- | --: |',
    categoryRows,
    '',
    '**Fix next**',
    '',
    fixes,
    '',
    `<sub>Generated by <a href="${REPO_URL}">StarForge</a>. Push a commit to refresh.</sub>`,
  ].join('\n')
}
